FROM node:18 as build
WORKDIR /app
COPY . .
RUN rm -rf node_modules && rm -rf dist
RUN npm install -g @nestjs/cli
RUN yarn install
RUN yarn build

FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/dist .
COPY --from=build /app/node_modules ./node_modules
EXPOSE 6000
CMD ["node", "main"]